name: Generate Windows executable
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"  # Run only when a new version tag (e.g., v1.0.0) is pushed

jobs:
  gen-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install additional dependencies
        run: pip install PyInstaller
      - name: Generate executable
        run: pyinstaller --onefile --name "EDH_matchmaker" --icon=media/icon.ico --add-data "ui\\;ui" run_ui.py
      - name: Remove build files and move the executable to root
        run: |
          rm -r build
          rm EDH_matchmaker.spec
          mv dist/EDH_matchmaker.exe .
      # Upload executable as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: EDH_matchmaker
          path: EDH_matchmaker.exe
